spring:
  kafka:
    properties:
      security.protocol: ${OCI_STREAMING_SECURITY_PROTOCOL:SASL_SSL}
      sasl.mechanism: ${OCI_STREAMING_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${OCI_STREAMING_SASL_JAAS_CONFIG}

demo:
  failover:
    secondary-security-protocol: ${DEMO_FAILOVER_SECONDARY_SECURITY_PROTOCOL:${OCI_STREAMING_SECURITY_PROTOCOL:SASL_SSL}}
    secondary-sasl-mechanism: ${DEMO_FAILOVER_SECONDARY_SASL_MECHANISM:${OCI_STREAMING_SASL_MECHANISM:PLAIN}}
    secondary-sasl-jaas-config: ${DEMO_FAILOVER_SECONDARY_SASL_JAAS_CONFIG:${OCI_STREAMING_SASL_JAAS_CONFIG:}}
